import { describe, it, expect } from 'vitest';
import { cssOutputPlugin } from '@/css-output.js';
import type { TokenGraph } from '@dtt/core';

function makeGraph(): TokenGraph {
  return {
    nodes: new Map([
      ['color.primary', { path: ['color', 'primary'], value: '#3b82f6', rawValue: '#3b82f6', type: 'color' }],
      ['spacing.base', { path: ['spacing', 'base'], value: { value: 1, unit: 'rem' }, rawValue: '{"value":1,"unit":"rem"}', type: 'dimension' }],
    ]),
    order: ['color.primary', 'spacing.base'],
  };
}

describe('cssOutputPlugin', () => {
  it('writes tokens.css to the output dir', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist').hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written).toHaveLength(1);
    expect(written[0].path).toMatch(/tokens\.css$/);
  });

  it('wraps variables in :root {}', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist').hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written[0].content).toContain(':root {');
  });

  it('serializes scalar color', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist').hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written[0].content).toContain('--color-primary: #3b82f6;');
  });

  it('serializes composite dimension token', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist').hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written[0].content).toContain('--spacing-base: 1rem;');
  });

  it('applies prefix when provided', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist', { prefix: 'dtt' }).hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written[0].content).toContain('--dtt-color-primary: #3b82f6;');
  });

  it('includes generated-by header comment', () => {
    const written: Array<{ path: string; content: string }> = [];
    cssOutputPlugin('./dist').hooks!.output!({
      graph: makeGraph(),
      write: (p, c) => written.push({ path: p, content: c }),
    });
    expect(written[0].content).toMatch(/^\/\* Generated by DTT \*\//);
  });
});
