import { join } from 'node:path';
import type { Plugin } from '@dtt/core';
import { serializeToCSS } from '@/css-serializer.js';

export function cssOutputPlugin(outputDir: string, options?: { prefix?: string }): Plugin {
  return {
    name: 'dtt:css-output',
    hooks: {
      output({ graph, write }) {
        const prefix = options?.prefix ? `${options.prefix}-` : '';
        const lines: string[] = ['/* Generated by DTT */', ':root {'];
        for (const key of graph.order) {
          const node = graph.nodes.get(key)!;
          const varName = `--${prefix}${key.replaceAll('.', '-')}`;
          const declarations = serializeToCSS(varName, node.value, node.type);
          for (const decl of declarations) {
            lines.push(`  ${decl}`);
          }
        }
        lines.push('}');
        write(join(outputDir, 'tokens.css'), lines.join('\n') + '\n');
      },
    },
  };
}
